Use `#[error(transparent)]` for `ReadlineError::IO`
thiserror's `error(transparent)` attribute causes the `Display` and `source()`
of the annotated error variant to forward directly to the inner error.  In
contrast, the current `Display` for I/O errors adds basically nothing to the
inner `io::Error`'s `Display`, and if a `ReadlineError` were to be wrapped in a
type like `anyhow::Error` that displays the full error chain on exit, the I/O
error message would be output twice, e.g.:

    Error: io: input pipe broke

    Caused by:
        input pipe broke

By using `error(transparent)` instead, the output changes to just:

    Error: input pipe broke